clean channel for charmcraft publish from disallowed signs
canonical/charming-actions pull request #91
Opened 2023-03-15 13:43 UTC by beliaev-maksim

2023-03-15 20:22 UTC, simskij commented
This does not look to me like something the action should do, to be honest. Can you please explain why this is needed? My view is that the user needs to make sure they pass valid channel names to the action, rather than the action trying to rectify it for them.

2023-03-15 21:55 UTC, beliaev-maksim commented
overall, charmhub has its own set of restrictions on the name. One of the use cases is that you publish charm to the branch on charmhub with the same branch name as your git branch. However, git branches have more flexibility on names, for example `_` which is not supported on charmhub. So, we can just filter down such things in action. Otherwise we need to do it in all the repos

2023-03-16 08:02 UTC, simskij requested changes
Suggest switching to an explicit regex construct to make it easier for others to parse.

2023-03-16 08:02 UTC, simskij commented on src/services/charmcraft/charmcraft.ts
> +    const allowedChannel = channel.replace(/_|[^\w\-/]/gi, '');
```suggestion
    const allowedChannel = channel.replace(/[^a-zA-Z0-9\-\/]/gi, '');
```

2023-03-16 08:09 UTC, simskij commented on src/services/charmcraft/charmcraft.ts
> +    const allowedChannel = channel.replace(/[^a-zA-Z0-9\-\/]/gi, '');
```suggestion
    const allowedChannel = channel.replace(/[^a-zA-Z0-9\-/]/gi, '');
```

2023-03-16 08:09 UTC, simskij approved these changes

2023-03-16 08:11 UTC, merged

2023-03-27 15:35 UTC, ca-scribner commented
This was reverted by #93